# Generated by Django 5.1.4 on 2025-01-17 16:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('phonenumber', models.CharField(max_length=15, unique=True)),
                ('birthday', models.DateField(default=datetime.date(2000, 1, 1), null=True)),
                ('password', models.CharField(blank=True, max_length=300, null=True)),
                ('password2', models.CharField(max_length=300)),
                ('image', models.ImageField(default='default.png', upload_to='profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
